### ISSUE TITLE
Upgrade to Open Layers 7

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper-maps#204]
I tried updating to OL 7, but this requires also updating ol-mapbox-style. Updating this to 8.0.4 worked: f1f48e84c6b7f270b1a296e6d4df2a1be5094d73, but for 8.0.5 until 8.1.1 I get this error:

```
Package path . is not exported from package /home/me/code/routing/graphhopper/gh-maps-react/node_modules/ol-mapbox-style (see exports field in /home/me/code/routing/graphhopper/gh-maps-react/node_modules/ol-mapbox-style/package.json)
```

and for `8.1.2` or higher I get:

```
utils.js:158 Uncaught TypeError: Cannot read properties of undefined (reading 'style')
    at utils.js:158:8
    at ./node_modules/ol-mapbox-style/dist/olms.js (utils.js:158:8)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/layers/UseBackgroundLayer.tsx (UseBackgroundLayer.tsx:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/App.tsx (App.tsx:25:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
```
And also the same for latest olms (9.1.0) + OL 7.0.0

And here is the diff between 8.1.1 and 8.1.2: https://github.com/openlayers/ol-mapbox-style/compare/v8.1.1...v8.1.2

**Comment by easbar** [comment]
It seems like the error is triggered already by the import statement even when we do not call `apply` at all.

```js
import { apply} from 'ol-mapbox-style'

if (false) {
   apply(null as any, null as any);
}
```

I have no idea how to fix this or even further debug the issue. So the only possible solutions that I can think of right now are either removing the three vector background layers (2xmap tiler + mapillion) and olms, or just keeping Open Layers 6 for now :(

**Comment by easbar** [comment]
It could also be related to our tsconfig.json file, but I could not make it work: https://github.com/graphhopper/graphhopper-maps/blob/46107c784c98b1fba4c92d25e4c9a0810c8c26c0/tsconfig.json#L17-L27

**Comment by easbar** [comment]
This somehow must be related to this change where they added the dist folder to their distribution: https://github.com/openlayers/ol-mapbox-style/compare/v8.0.4...v8.0.5.
I don't fully understand this, but when we switch to using ES6 modules in the typescript config: #264 it seems to work.
